First version of the layout
relativemodder/androidToDo pull request #1
Opened 2023-01-24 17:03 UTC by relativemodder

2023-01-25 17:32 UTC, Alexandr-Prokin requested changes
В целом хорошо

2023-01-25 17:32 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:contentDescription="@string/imageBgPlaceholder"
тут ошибка

2023-01-25 17:32 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="0.0"
все что заканчивается на _bias удаляем, подумай куда закрепить элемент

2023-01-25 17:32 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +    <LinearLayout
LinearLayout тут не нужен

2023-01-25 17:32 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        app:srcCompat="@drawable/bg01" />
переименовать картинку по содержимому

2023-01-25 17:32 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +            android:gravity="center"
gravity удаляем, через margin нужно сделать

2023-01-25 17:32 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="320dp"
от точных размеров избавляемся

2023-01-25 17:32 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +            android:maxWidth="320dp"
удаляем

2023-01-25 17:32 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="320dp"
от точных размеров избавляемся

2023-01-25 17:32 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +            android:background="@drawable/corner_input_style"
хорошее решение =)

2023-01-25 17:32 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +            android:shadowColor="#7C000000"
цвета тоже в ресурсы, и название по месту использования например: button_shadow_color

2023-01-25 17:32 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +            android:textColor="#FFC107"
в ресурсы

2023-01-25 17:36 UTC, merged

2023-01-26 19:50 UTC, relativemodder commented on app/src/main/res/layout/activity_main.xml
> +            android:gravity="center"
textAlign не вариант?

2023-01-26 19:51 UTC, relativemodder commented on app/src/main/res/layout/activity_main.xml
> +    <LinearLayout
LinearLayout нужен, чтобы поверх картинки наложить контент, почему его не использовать? Или тут подразумевается, что при скролле картинка тоже должна двигаться (Я про два кружочка сверху)

2023-01-26 19:51 UTC, relativemodder commented on app/src/main/res/layout/activity_main.xml
> +        android:contentDescription="@string/imageBgPlaceholder"
исправил

2023-01-26 19:51 UTC, relativemodder commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="0.0"
исправил

2023-01-26 19:52 UTC, relativemodder commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="320dp"
без layout_width вылезает ошибка, это обязательный атрибут

2023-01-26 19:53 UTC, relativemodder commented on app/src/main/res/layout/activity_main.xml
> +            android:maxWidth="320dp"
смотреть комментарий сверху

2023-01-26 19:54 UTC, relativemodder commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="320dp"
то же самое, это обязательный атрибут

2023-01-26 19:54 UTC, relativemodder commented on app/src/main/res/layout/activity_main.xml
> +            android:background="@drawable/corner_input_style"
благодарю

2023-01-26 19:59 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +    <LinearLayout
При скроле будет двигаться все, поэтому LinearLayout тут не нужен.

2023-01-26 19:59 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +            android:gravity="center"
нет

2023-01-26 20:01 UTC, relativemodder commented on app/src/main/res/layout/activity_main.xml
> +            android:shadowColor="#7C000000"
вынес

2023-01-26 20:01 UTC, relativemodder commented on app/src/main/res/layout/activity_main.xml
> +            android:textColor="#FFC107"
вынес

2023-01-26 20:02 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="320dp"
Ну я и не имел в виду удалить атрибут, есть параметры, которые динамически задают размеры, wrap_content, match_parent

2023-01-26 20:03 UTC, relativemodder commented on app/src/main/res/layout/activity_main.xml
> +        app:srcCompat="@drawable/bg01" />
переименовал