Changes:
relativemodder/androidToDo pull request #3
Opened 2023-01-26 21:02 UTC by relativemodder

- Fixed hardcode with colors
- Image placeholder and Id both have more sense in name
- Fixed the **WHOLE** layout
- Now primary and secondary activity colors are yellow and orange

2023-01-29 08:14 UTC, Alexandr-Prokin requested changes
Картинку с человеком тоже надо переименовать

2023-01-29 08:14 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_gravity="start"
Если удалить этот параметр, изменится как то положение элемента?

2023-01-29 08:14 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="@dimen/margin_left_right"
Если marginStart и marginEnd имеют одинаковые значения, то можно использовать .... ? Во всех элементах это исправь

2023-01-29 08:14 UTC, Alexandr-Prokin commented on app/src/main/java/com/example/todoapp/MainActivity.kt
> +        supportRequestWindowFeature(Window.FEATURE_NO_TITLE)
Это не очень хорошее решение, нужно найти другое решение

2023-02-08 18:40 UTC, relativemodder commented
test

2023-02-08 18:40 UTC, closed without merging